# Generated by Django 5.0.4 on 2024-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansaauser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
