# Generated by Django 5.0.4 on 2024-05-01 13:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_ansaaapproveduser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansaaapproveduser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
