# Generated by Django 5.0.4 on 2024-05-01 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_ansaaapproveduser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansaaapproveduser',
            options={'verbose_name': 'Ansaa Approved User', 'verbose_name_plural': 'Ansaa Approved User List'},
        ),
        migrations.AddField(
            model_name='ansaaapproveduser',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
