# Generated by Django 5.0.4 on 2024-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansaaapproveduser',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
    ]
