# Generated by Django 5.0.4 on 2024-05-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_ansaaapproveduser_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnsaaApprovedUser',
        ),
        migrations.AlterModelOptions(
            name='ansaauser',
            options={'ordering': ['-start_date'], 'verbose_name': 'Ansa User', 'verbose_name_plural': 'Ansa Users'},
        ),
    ]
