# Generated by Django 5.0.4 on 2024-05-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_ansaaapproveduser_alter_ansaauser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='user',
        ),
    ]
