# Generated by Django 5.0.4 on 2024-05-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billboards',
            options={'ordering': ['-status'], 'verbose_name': 'Billboard', 'verbose_name_plural': 'Billboards'},
        ),
    ]
