# Generated by Django 5.0.4 on 2024-05-13 16:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0002_alter_billboards_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='billboards',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='dimension',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billboards',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
