# Generated by Django 5.0.4 on 2024-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0003_zones_alter_billboards_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboards',
            name='billboard_name',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
