# Generated by Django 5.0.4 on 2024-05-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0004_billboards_billboard_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zones',
            options={'verbose_name': 'Sub zone', 'verbose_name_plural': 'Sub zones'},
        ),
        migrations.RenameField(
            model_name='billboards',
            old_name='billboard_name',
            new_name='asset_name',
        ),
        migrations.AddField(
            model_name='billboards',
            name='asset_type',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('static', 'Static')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='category',
            field=models.CharField(choices=[('free standing signs', 'Free standing signs'), ('projecting signs', 'Projecting signs'), ('wall signs', 'Wall signs'), ('special advertisement', 'Special advertisement')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='sub_zone',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='media_asset.zones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billboards',
            name='zone',
            field=models.CharField(choices=[('normal zone', 'Normal zone'), ('Restricted zone', 'Restricted zone')], default=True, max_length=50),
            preserve_default=False,
        ),
    ]
