# Generated by Django 5.0.4 on 2024-05-14 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0008_userzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboards',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
