# Generated by Django 5.0.4 on 2024-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0010_alter_billboards_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboards',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
