# Generated by Django 5.0.4 on 2024-05-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0011_alter_billboards_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboards',
            name='sub_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_asset.zones'),
        ),
    ]
