# Generated by Django 5.0.4 on 2024-05-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0013_alter_billboards_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboards',
            old_name='agent',
            new_name='user',
        ),
    ]
