# Generated by Django 5.0.4 on 2024-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0014_rename_agent_billboards_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboards',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
