# Generated by Django 5.0.4 on 2024-05-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0015_alter_billboards_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboards',
            name='user',
        ),
    ]
