# Generated by Django 5.0.4 on 2024-05-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_asset', '0017_billboards_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboards',
            name='user',
        ),
    ]
